name: Deploy to Backend lawptimize
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select the branch to run the workflow"
        required: true
        default: "master"
        type: choice
        options:
          - master
env:
  AWS_ACCOUNT_ID: 803664810774
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_REPO_NAME: lawptimize
  IMAGE_TAG: latest
  REPOSITORY_URI: 803664810774.dkr.ecr.us-east-1.amazonaws.com/lawptimize

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Docker Login
        run: |
          aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com
      
      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Docker Tag
        run: docker tag ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }} ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }}

      - name: Docker Push
        run: docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }}

      # - name: ECS Update
      #   run: |
      #     aws ecs update-service \
      #     --cluster lipiq \
      #     --service lipiq-bot-service \
      #     --force-new-deployment \
      #     --region ${{ env.AWS_DEFAULT_REGION }}
